version: '3'

networks:
  scan-api:
    external: false

services:

  postgres:
    image: postgres:14.2-alpine
    container_name: scan-database
    networks:
      - scan-api
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    ports:
      - '5432:5432'
    volumes:
      - scan-pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  scan-pgdata:
    external: false
