version: "3"

networks:
 scan-api:
   external: true

services:
  scan-web-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scan-web-api
    ports:
      - "3031:3031"
    networks:
      - scan-api
    depends_on:
      - postgres
      - crawler
    restart: on-failure
    environment:
      - PORT=3031
      - POSTGRES_USER=polkastats
      - POSTGRES_PASSWORD=polkastats
      - POSTGRES_DATABASE=polkastats
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  postgres:
    image: postgres:14.2-alpine
    container_name: scan-database
    networks:
      - scan-api
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - scan-pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

# TODO: Add definitions for Squid Archive

volumes:
  scan-pgdata:
    external: false
