version: "3"

networks:
  scan:
    external: false

services:
  scan-web-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scan-web-api
    ports:
      - "3031:3031"
    networks:
      - scan
    depends_on:
      - postgres
      - crawler
    restart: on-failure
    environment:
      - PORT=3031
      - POSTGRES_USER=polkastats
      - POSTGRES_PASSWORD=polkastats
      - POSTGRES_DATABASE=polkastats
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432

  postgres:
    image: postgres:14.2-alpine
    container_name: scan-database
    networks:
      - scan
    environment:
      - POSTGRES_USER=polkastats
      - POSTGRES_PASSWORD=polkastats
      - POSTGRES_DB=polkastats
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    ports:
      - "3032:5432"
    volumes:
      - scan-pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    container_name: scan-crawler
    networks:
      - scan
    depends_on:
      - crawler-migrations
    restart: on-failure
    environment:
      - NODE_ENV=production
      - ARCHIVE_GQL_URL=${ARCHIVE_GQL_URL}
      - CHAIN_WS_URL=${CHAIN_WS_URL}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=polkastats
      - POSTGRES_PASSWORD=polkastats
      - POSTGRES_DATABASE=polkastats
      - PROMETHEUS_PORT=9003
      - HOST_CRAWLER=0.0.0.0

  crawler-migrations:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    container_name: scan-crawler-migrations
    networks:
      - scan
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - NODE_ENV=production
      - ARCHIVE_GQL_URL=${ARCHIVE_GQL_URL}
      - CHAIN_WS_URL=${CHAIN_WS_URL}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=polkastats
      - POSTGRES_PASSWORD=polkastats
      - POSTGRES_DATABASE=polkastats
      - PROMETHEUS_PORT=9003
      - HOST_CRAWLER=0.0.0.0
    entrypoint: ["npm", "run", "db:migration:run"]


volumes:
  scan-pgdata:
    external: false
