name: Build Docker image

on:
  workflow_call:
    inputs:
      image:
        type: string
        description: image
        default: uniquenetwork/unique-web
      tag:
        type: string
        description: tag
        required: true
      dockerfile:
        type: string
        description: dockerfile path
        default: ./Dockerfile
      target:
        type: string
        description: build target
        required: false
      is_latest:
        type: string
        description: should add latest tag
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.image }}:${{ inputs.tag }}-${{ github.sha }}
      -
        name: Build and push latest
        if: ${{ inputs.is_latest == 'true' }}
        uses: docker/build-push-action@v4
        with:
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.image }}:${{ inputs.tag }}-latest
