name: Build and push docker images

on:
  workflow_dispatch:
    inputs:
      is_latest:
        type: string
        description: should add latest tag
        default: "false"

jobs:
  build-crawler:
    name: Build Crawler
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      tag: scan-backend-crawler
      dockerfile: Dockerfile.crawler
      is_latest: ${{ github.event.inputs.is_latest }}

  build-web-api:
    name: Build Web API
    uses: ./.github/workflows/build-docker-image.yml
    secrets: inherit
    with:
      tag: scan-backend-web-api
      is_latest: ${{ github.event.inputs.is_latest }}
