name: Build and push docker images

on:
  workflow_dispatch:

jobs:
  build-crawler:
    name: Build Crawler
    uses: ./build-docker-image.yml
    secrets: inherit
    with:
      tag: scan-backend-crawler
      dockerfile: Dockerfile.crawler

  build-web-api:
    name: Build Web API
    uses: ./build-docker-image.yml
    secrets: inherit
    with:
      tag: scan-backend-web-api
