name: Deploy to Demo VM

on:
#  push:
#    branches:
#      - demo
  workflow_dispatch:

jobs:
  run-gitlab-pipeline:
    name: Run gitlab pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Trigger gitlab
        uses: wei/curl@v1
        with:
          args: -X POST -F token=${{ secrets.UNIQUE_GITLAB_TOKEN_DEMO }} -F ref=master -F variables[REMOTE_COMMIT]=${GITHUB_SHA} -F variables[DEPLOY_TO]=stage https://gitlab.uniquenetwork.dev/api/v4/projects/57/trigger/pipeline
